sonar.projectKey=notes-app-fullstack
sonar.host.url=http://localhost:9000
sonar.token=sqp_bb79d53cae318f8bde19e37dcc920f5c67bca66c
sonar.sources=backend,frontend/src
sonar.exclusions=**/node_modules/**,**/tests/**,**/*.test.jsx,frontend/dist/**,**/__mocks__/**