sonar.projectKey=notes-app-fullstack
sonar.sources=backend,frontend/src
sonar.host.url=http://localhost:9000
sonar.exclusions=**/node_modules/**,**/tests/**,**/*.test.jsx,frontend/dist/**,**/__mocks__/**
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info