sonar.projectKey=notes-app-fullstack
sonar.host.url=http://localhost:9000
sonar.token=sqp_a8ec5cabff62a619af47f8f999579564651fb79c
sonar.sources=backend,frontend/src
sonar.exclusions=**/node_modules/**,**/tests/**,**/*.test.jsx,frontend/dist/**,**/__mocks__/**,**/coverage/**,**/lcov-report/**
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info